feat: dynamic languages based on document
sanity-io/sanity-plugin-internationalized-array pull request #7
Opened 2023-01-24 16:21 UTC by gaauwe

Great work so far on this plugin @SimeonGriggs! Loading the languages asynchronously helps us a lot. In our case (as discussed with Tom in our [Sanity x Belsimpel trial](https://belsimpel.slack.com/archives/C04JSRMF26L)), we needed to load languages based on data in a document, so I want to take this opportunity to share this feature.

### Feature
I looked into multiple options for providing the document as parameter to the language callback, but the tricky thing is that the document changes a lot while editing. This made it so that the languages kept reloading and reloading. In the end, I wound up building a solution that's very similar to Sanity [list previews](https://www.sanity.io/docs/previews-list-views#770fd57a8f95). You can select your own fields in the document that should trigger a reload, and you get those fields directly in the language callback:

 ```tsx
{
	select: {
		markets: 'markets',
	},
	languages: (client, { markets }) =>
		client.fetch(groq`*[_type == "language" && market in $markets]{id,title}`, { markets }),
}
```

### Possible optimization
This works great already, but I have a small optimization in mind that I could use your help on. In our case, we want to load languages based on an array of references. The minor issue that we're seeing is that once you add an item to the array, it updates the document with an empty reference already before you choose a value: [UI](https://user-images.githubusercontent.com/1271226/214344864-46100bc5-28fe-4ebd-8efd-d8a54efe4ba8.png), [data](https://user-images.githubusercontent.com/1271226/214344900-0caf407d-e35d-4237-8287-bf089fe0be5f.png). Ideally we'd only want to reload languages if an actual reference value is filled in, do you know if there is a good way to fix this?

2023-01-24 16:32 UTC, SimeonGriggs commented
Thanks for this @gaauwe! A feature I'd wanted myself :) 

I've tagged @stipsan on this since he added the function to fetch Languages and may have thoughts on the work here.

2023-01-25 01:53 UTC, stipsan requested changes
Looks great! ✨ I'm only marking this as a `Request changes` due to the `lodash` dependency, the other suggestions are, just that, suggestions 😌

2023-01-25 01:53 UTC, stipsan commented on src/components/InternationalizedArray.tsx
> +  const selectedValue = getSelectedValue(options.select, document)
Since V3 haven't been optimised its context providers and `useContext` hooks to only rerender when changed (we had to chose between spending time on moving to a React 18 baseline or fix context state, so we went with 18 as it gives us more opportunities to fix context state long term) it's a good idea to add `useDeferredValue` and `useMemo` here to avoid blocking the UI if there's a lot of multiplayer activity happening in a document:
```suggestion
  const {value: document} = useFormBuilder()
  const deferredDocument = useDeferredValue(document)
  const selectedValue = useMemo(() =>
    getSelectedValue(options.select, deferredDocument)
  , [getSelectedValue, options.select, deferredDocument])
```

2023-01-25 01:53 UTC, stipsan commented on src/components/getSelectedValue.ts
> +  }, {})
To answer your "Possible optimization" question, we could specifically look for empty references here and filter them out since it's unlikely that anyone wants/needs them to be returned by `options.select`:

```suggestion
  const selection: Record<string, string> = select || {}
  const selectedValue: Record<string, unknown> = {}
  for (const [key, path] of Object.entries(selection)) {
    let value = get(document, path)
    if(Array.isArray(value)) {
      // If there are references in the array, ensure they have `_ref` set, otherwise they are considered empty and can safely be ignored
      value = value.filter(
        item => 
          typeof item === 'object' 
          ? item?._type === 'reference' && '_ref' in item 
          : true
      )
    }
    selectedValue[key] = value
  }
```

2023-01-25 12:45 UTC, gaauwe commented on package.json
> +    "lodash": "^4.17.21",
Good one! I was indeed not sure if we could rely on deduping alone, so better be safe than sorry. Installed both the specific lodash package plus types.

2023-01-25 12:46 UTC, gaauwe commented on src/components/InternationalizedArray.tsx
> +  const selectedValue = getSelectedValue(options.select, document)
Great suggestion, by doing this we don't even get the loading state anymore after changing languages. It now seems to fetch in the background, which in my opinion makes this change quite useful.

2023-01-25 12:59 UTC, stipsan commented on src/components/InternationalizedArray.tsx
> +  const selectedValue = getSelectedValue(options.select, document)
Nice, I thought only the `useTransition` and `startTransition` APIs could have that effect 🤯 At the time it felt a bit risky to make React 18 the baseline, but it does start to look like it was the right decision for our ecosystem 😮‍💨 It's just so nice to have more strategies available when dealing with async stuff and adapting to IO constraints 😌

2023-01-25 21:49 UTC, stipsan approved these changes
Perfect, let's ship! 🚀

2023-01-25 21:49 UTC, merged